import { React, AllWidgetProps, DataSourceComponent, DataSource } from 'jimu-core'
import { Button, Label, Select, Option, TextInput, Alert } from 'jimu-ui'
import { IMConfig, SourceConfig, Statistic } from '../config'
import { aggregate, AggregateRow } from './aggregation'
import './style.css'

const fallback: SourceConfig = { dateField: '', valueField: '', valueType: 'number', statistic: 'count', period: 'epi-week', weekMode: 'iso', dateConvention: 'dmy', outbreakStart: '', filterMode: 'cumulative' }
const t = (fr: boolean, en: string, f: string) => fr ? f : en
const format = (n: any, fr: boolean) => { if (n === null || n === undefined || n === '') return '—'; if (typeof n === 'string') { const d = new Date(n); return !isNaN(d.getTime()) && n.includes('T') ? d.toLocaleDateString(fr ? 'fr-FR' : 'en-US') : n } return Number.isInteger(n) ? n.toLocaleString(fr ? 'fr-FR' : 'en-US') : n.toLocaleString(fr ? 'fr-FR' : 'en-US', { maximumFractionDigits: 2 }) }

interface SourceViewProps { ds: DataSource; sourceId: string; source: SourceConfig; props: AllWidgetProps<IMConfig>; fr: boolean; accentColor: string }
function SourceView({ ds, sourceId, source, props, fr, accentColor }: SourceViewProps) {
  const c = { ...fallback, ...(source || {}) }; const field = c.dateField || ''
  const [rows, setRows] = React.useState<AggregateRow[]>([]); const [invalid, setInvalid] = React.useState(0); const [selected, setSelected] = React.useState(''); const [playing, setPlaying] = React.useState(false); const [speed, setSpeed] = React.useState(1200); const [cumulative, setCumulative] = React.useState(false); const [periodsOpen, setPeriodsOpen] = React.useState(true); const timer = React.useRef<any>(null)
  React.useEffect(() => () => { if (timer.current) clearInterval(timer.current) }, [])
  React.useEffect(() => { setPeriodsOpen(rows.length <= 12) }, [rows.length])
  React.useEffect(() => { if (!playing || !rows.length) return; timer.current = setInterval(() => setSelected(current => { const i = rows.findIndex(r => r.key === current); return rows[(i + 1) % rows.length].key }), speed); return () => clearInterval(timer.current) }, [playing, rows, speed])
  React.useEffect(() => {
    let cancelled = false
    if (!field) { setRows([]); setSelected(''); return () => { cancelled = true } }
    // A previous timeline selection must never constrain the new aggregation window.
    // Clear the widget-specific query before rebuilding all periods.
    const queryId = `${props.id}-${sourceId}`
    ds.updateQueryParams({ where: '1=1' } as any, queryId)
    ds.query({ where: '1=1', outFields: ['*'], returnGeometry: false, pageSize: 10000 } as any).then((result: any) => { if (cancelled) return; const output = aggregate(result.records || [], field, c.period, c.weekMode, c.outbreakStart, c.dateConvention, c.statistic, c.valueField, c.valueType); setRows(output.rows); setInvalid(output.invalid); setSelected(output.rows[0]?.key || '') }).catch(() => { if (!cancelled) { setRows([]); setInvalid(0); setSelected('') } })
    return () => { cancelled = true }
  }, [ds, field, c.period, c.weekMode, c.outbreakStart, c.dateConvention, c.statistic, c.valueField, c.valueType, props.id, sourceId])
  React.useEffect(() => { const row = rows.find(r => r.key === selected); const queryId = `${props.id}-${sourceId}`; if (!field || c.filterMode === 'none') { ds.updateQueryParams({ where: '1=1' } as any, queryId); return }; if (!row) return; const safeField = field.replace(/[^A-Za-z0-9_]/g, ''); const iso = (d: Date) => d.toISOString().slice(0, 19).replace('T', ' '); const start = c.filterMode === 'cumulative' ? rows[0].start : row.start; ds.updateQueryParams({ where: `${safeField} >= DATE '${iso(start)}' AND ${safeField} < DATE '${iso(row.end)}'` } as any, queryId) }, [selected, rows, field, c.filterMode, ds, props.id, sourceId])
  const count = rows.reduce((n, r) => n + r.count, 0); const numericMetric = ['sum', 'mean', 'median'].includes(c.statistic) || (['min', 'max'].includes(c.statistic) && c.valueType === 'number'); const metricTotal = c.statistic === 'sum' ? rows.reduce((n, r) => n + (typeof r.value === 'number' ? r.value : 0), 0) : (rows[rows.length - 1]?.value ?? 0); const peakRow = rows.length ? rows.reduce((best, row) => (typeof row.value === 'number' && row.value > (typeof best.value === 'number' ? best.value : -Infinity)) ? row : best, rows[0]) : undefined; const peak = peakRow?.value ?? '—'; const canCumulative = c.statistic === 'count' || numericMetric; const label = c.label || sourceId; const periodLabel = rows.find(r => r.key === selected)?.label || '—'; const filterLabel = c.filterMode === 'none' ? t(fr, 'All data', 'Toutes les données') : c.filterMode === 'cumulative' ? t(fr, 'Progressive', 'Progressif') : t(fr, 'Single period', 'Période unique')
  return <section className="epi-source" style={{ '--epi-accent': accentColor } as any}><div className="epi-heading"><div><h3>{label}</h3><span>{c.statistic === 'count' ? t(fr, 'Total records', 'Nombre total d’enregistrements') : `${c.statistic} — ${c.valueField || t(fr, 'measure not selected', 'mesure non sélectionnée')}`}</span></div><div className="epi-heading-right"><span className="epi-badge">{format(count, fr)}</span><small>{t(fr, 'total records', 'enregistrements au total')}</small></div></div><div className="epi-active-period"><strong>{t(fr, 'Displayed period', 'Période affichée')} : {periodLabel}</strong><span>{filterLabel}</span></div>
    {!field && <Alert type="info">{t(fr, 'Choose a date field in the Content settings.', 'Choisissez un champ date dans le panneau Contenu.')}</Alert>}{field && !rows.length && <div className="epi-empty">{t(fr, 'No valid dates found.', 'Aucune date valide trouvée.')}</div>}{invalid > 0 && <div className="epi-warning">{invalid} {t(fr, 'record(s) ignored: unrecognised date', 'enregistrement(s) ignoré(s) : date non reconnue')}</div>}
    {rows.length > 0 && <div className="epi-summary"><span><b>{format(count, fr)}</b><small>{t(fr, 'total records', 'enregistrements au total')}</small></span><span><b>{format(peak, fr)}</b><small>{t(fr, 'peak value', 'valeur du pic')}<br />{peakRow?.label || '—'}</small></span><span><b>{rows.length}</b><small>{t(fr, 'periods', 'périodes')}</small></span></div>}
    <div className="epi-toolbar"><Button size="sm" onClick={() => setPlaying(!playing)} disabled={!rows.length}>{playing ? '■' : '▶'} {playing ? t(fr, 'Stop', 'Arrêter') : t(fr, 'Play', 'Lire')}</Button><Select value={String(speed)} onChange={e => setSpeed(Number(e.target.value))}><Option value="2000">{t(fr, 'Slow', 'Lent')}</Option><Option value="1200">Normal</Option><Option value="600">{t(fr, 'Fast', 'Rapide')}</Option></Select><label className="epi-check"><input type="checkbox" checked={cumulative} disabled={!canCumulative} onChange={e => setCumulative(e.target.checked)} /> {t(fr, 'Cumulative', 'Cumulé')}</label></div>
    <div className="epi-periods-header"><button className="epi-collapse" onClick={() => setPeriodsOpen(open => !open)} aria-expanded={periodsOpen}>{periodsOpen ? '⌃' : '⌄'} {periodsOpen ? t(fr, 'Hide periods', 'Masquer les périodes') : t(fr, 'Show periods', 'Afficher les périodes')} ({rows.length})</button><span>{selected ? rows.find(r => r.key === selected)?.label : ''}</span></div>{periodsOpen && <div className="epi-periods">{rows.map((r, i) => <button className={selected === r.key ? 'selected' : ''} key={r.key} onClick={() => { setSelected(r.key); setPlaying(false) }}><strong>{r.label}</strong><span>{format(cumulative && canCumulative ? rows.slice(0, i + 1).reduce((n, x) => n + (typeof x.value === 'number' ? x.value : 0), 0) : r.value, fr)}</span></button>)}</div>}
    <div className="epi-foot">{selected ? `${t(fr, 'Active filter', 'Filtre actif')} : ${rows.find(r => r.key === selected)?.label}` : t(fr, 'No period selected', 'Aucune période sélectionnée')} {selected && <Button size="sm" onClick={() => { ds.updateQueryParams({ where: '1=1' } as any, `${props.id}-${sourceId}`); setSelected('') }}>{t(fr, 'Clear filter', 'Réinitialiser')}</Button>}</div>
  </section>
}

export default function Widget(props: AllWidgetProps<IMConfig>) {
  const config: any = props.config || {}; const get = (key: string) => typeof config.get === 'function' ? config.get(key) : config[key]; const fr = (get('locale') || 'fr').toLowerCase().startsWith('fr'); const selected: any[] = props.useDataSources ? (props.useDataSources.toArray ? props.useDataSources.toArray() : props.useDataSources) : []
  if (!selected.length) return <div className="epi-widget epi-empty">{t(fr, 'Configure one or more line-list sources in the Content settings.', 'Configurez une ou plusieurs sources line-list dans le panneau Contenu.')}</div>
  const accentColor = get('accentColor') || '#1261a0'; const sourceMap = get('sources'); return <div className="epi-widget">{selected.map(use => { const id = use.dataSourceId; const saved = sourceMap?.get ? sourceMap.get(id) : sourceMap?.[id]; const source = saved?.toJS ? saved.toJS() : (saved || { ...fallback, dateField: get('dateField'), valueField: get('valueField'), valueType: get('valueType'), statistic: get('statistic'), period: get('period'), weekMode: get('weekMode'), dateConvention: get('dateConvention'), outbreakStart: get('outbreakStart'), filterMode: get('filterMode') }); return <DataSourceComponent key={id} useDataSource={use} widgetId={props.id}>{(ds: DataSource) => <SourceView ds={ds} sourceId={id} source={source} props={props} fr={fr} accentColor={accentColor} />}</DataSourceComponent> })}</div>
}
