import { React, AllWidgetSettingProps, DataSourceTypes, Immutable } from 'jimu-core'
import { DataSourceSelector } from 'jimu-ui/advanced/setting-components'
import { TextInput, Label, Select, Option } from 'jimu-ui'
import { IMConfig } from '../config'
export default function Setting(props: AllWidgetSettingProps<IMConfig>) {
  const config = props.config || Immutable({ locale: 'fr', period: 'epi-week', weekMode: 'iso', dateConvention: 'dmy', statistic: 'count', dateField: '', valueField: '', outbreakStart: '' }); const use = props.useDataSources
  const update = (key: string, value: any) => props.onSettingChange({ id: props.id, config: config.set(key, value) })
  return <div className="p-3"><Label>Line-list / source de données</Label><DataSourceSelector widgetId={props.id} types={[DataSourceTypes.FeatureLayer, DataSourceTypes.SceneLayer, DataSourceTypes.MapService]} mustUseDataSource useDataSources={use} onChange={ds => props.onSettingChange({ id: props.id, useDataSources: ds })} /><div className="mt-4"><Label>Champ date par défaut</Label><TextInput value={config.dateField || ''} placeholder="onset_date" onChange={e => update('dateField', e.target.value)} /></div><div className="mt-3"><Label>Statistique par défaut</Label><Select value={config.statistic || 'count'} onChange={e => update('statistic', e.target.value)}><Option value="count">Compter les enregistrements</Option><Option value="sum">Somme</Option><Option value="mean">Moyenne</Option><Option value="median">Médiane</Option><Option value="min">Minimum</Option><Option value="max">Maximum</Option><Option value="first">Première valeur</Option><Option value="last">Dernière valeur</Option><Option value="distinct">Valeurs distinctes</Option></Select></div><div className="mt-3"><Label>Champ numérique par défaut</Label><TextInput value={config.valueField || ''} placeholder="deaths, population" onChange={e => update('valueField', e.target.value)} /></div><div className="mt-3"><Label>Convention des dates ambiguës</Label><Select value={config.dateConvention || 'dmy'} onChange={e => update('dateConvention', e.target.value)}><Option value="dmy">Jour / mois / année</Option><Option value="mdy">Mois / jour / année</Option><Option value="auto">Automatique</Option></Select></div><div className="mt-3"><Label>Langue / Langage</Label><Select value={config.locale || 'fr'} onChange={e => update('locale', e.target.value)}><Option value="fr">Français</Option><Option value="en">English</Option></Select></div><div className="mt-3"><Label>Agrégation par défaut</Label><Select value={config.period || 'epi-week'} onChange={e => update('period', e.target.value)}><Option value="epi-week">Semaine épidémiologique</Option><Option value="month">Mois</Option><Option value="quarter">Trimestre</Option><Option value="year">Année</Option></Select></div></div>
}
